'use client'

import type { LucideIcon } from 'lucide-react'
import {
  ArrowRight,
  Award,
  BadgeCheck,
  Bell,
  Blocks,
  BookOpen,
  Box,
  Briefcase,
  Building,
  Calendar,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  Clock,
  Cloud,
  Code,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  Folder,
  Gift,
  Globe,
  Grid,
  Headphones,
  Heart,
  Layers,
  LifeBuoy,
  Link,
  List,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Minus,
  Monitor,
  Newspaper,
  Package,
  Palette,
  Pause,
  Phone,
  Play,
  Plug,
  Plus,
  RefreshCw,
  Repeat,
  Rocket,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  Table,
  Tag,
  Terminal,
  Timer,
  Trash,
  Trophy,
  Truck,
  Upload,
  User,
  Users,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react'

/**
 * Maps stored icon names (from the admin lucide dropdown) to lucide-react
 * components. Keep in sync with `LUCIDE_ICON_OPTIONS` in
 * `src/fields/lucideIcon.ts` — both use the same kebab-case names.
 */
const iconMap: Record<string, LucideIcon> = {
  'arrow-right': ArrowRight,
  award: Award,
  'badge-check': BadgeCheck,
  bell: Bell,
  blocks: Blocks,
  'book-open': BookOpen,
  box: Box,
  briefcase: Briefcase,
  building: Building,
  calendar: Calendar,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  check: Check,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  coins: Coins,
  compass: Compass,
  cpu: Cpu,
  'credit-card': CreditCard,
  database: Database,
  download: Download,
  edit: Edit,
  'external-link': ExternalLink,
  eye: Eye,
  'file-text': FileText,
  filter: Filter,
  folder: Folder,
  gift: Gift,
  globe: Globe,
  grid: Grid,
  headphones: Headphones,
  heart: Heart,
  layers: Layers,
  'life-buoy': LifeBuoy,
  link: Link,
  list: List,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  minus: Minus,
  monitor: Monitor,
  newspaper: Newspaper,
  package: Package,
  palette: Palette,
  pause: Pause,
  phone: Phone,
  play: Play,
  plug: Plug,
  plus: Plus,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  rocket: Rocket,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shopping-cart': ShoppingCart,
  sparkles: Sparkles,
  star: Star,
  table: Table,
  tag: Tag,
  terminal: Terminal,
  timer: Timer,
  trash: Trash,
  trophy: Trophy,
  truck: Truck,
  upload: Upload,
  user: User,
  users: Users,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
}

export const NavIcon: React.FC<{ name?: string | null; className?: string }> = ({ name, className }) => {
  if (!name) return null
  const Icon = iconMap[name]
  if (!Icon) return null
  return <Icon aria-hidden="true" className={className} />
}
